language: python
python: 2.7
sudo: false
matrix:
  include:
    - os: osx
      # Using "generic" because osx in Travis doesn't support python
      language: generic
install:
- "./.travis-workarounds.sh"
- '[ "$TRAVIS_OS_NAME" != osx ] || source ~/virtualenv/python2.7/bin/activate'
- "pip --version && pip install -U tox twine wheel"
script: tox -v -e py27,freeze
deploy:
  - provider: releases
    api_key:
      secure: nMcAFETPX5pvjMiqjEN07GVrkZxEQUy5CoWhEVcODvOO07KDStkYm0A3wBSubHcAfB6hDIeKuLJWlcLVdfjcDzdmy+3YaNbzwC5Ydrlz7gciQyQr8yUusjpvyWIwwiL4UEgjfi1+HA0nZo3AVACkWNWqFsXn7Qw/xasEbLUQpk+YrdMmXDizpArAaxOIEgpVWI5uRrPsGq3hOjhSAWrFtK93yw7B+Mtk2HEi3xc4gQ3rzZj1IAXsb00dTsKwKZ6R8aMTAC7C9Vt1dTZrPU3XwyPnt87GCLzIa+O9QiB0Ugt7cZfceHK3l029jjzWMRs3ArnyV9maCEMo1cKqCxrb7BxZw5+bLgVu3L16YnQT5GkJUoyIQoCuxjEWSG0whA6PJTnMsPBGszLvbHc5Hk1WjNLZgvT0+oYcrvqXhnIXpiCr00UBIcHdxu8EZkY7UdI3ls4Czmb6vxis4noWfd/aN/jH6tbXZKeiSqqJvdcI8mRcZXCzIqJsUmstOjPoZNRx+6ikkzNNLkM5Wd0vVh9tYlzY20hufizpejanm+OfrxXNJwF3/4Mm2p0eAv7VY9CuUnFr79B4Q2XjZLQ9KPwB4WL3v9ciN6uXHEvi6p2t4uraQjG7ni4XZAMqETXSeklpb08oSv6qGmef8ngn5YIcj0MQfTcyRBHDlUq57M060O4=
    file: "dist/shub"
    skip_cleanup: true
    on:
      tags: true
