
version: '{branch}-{build}'

install:
  - "SET PATH=C:\\Python27;C:\\Python27\\Scripts;%PATH%"
  - "python --version"
  - "pip install -U tox twine wheel"

# Build the binary after tests
build: false

environment:
  TOXENV: freeze

test_script:
  - tox

artifacts:
  - path: .\dist\shub.exe
    name: "shub Windows binary"
